import { TaxationMethod } from "../src/constants";

export const DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT = {
  make: "Toyota",
  msrp: 23000,
  sellingPrice: 21000,
  rv: 13110,
  isRVPercent: false,
  mf: 0.00125,
  leaseTerm: 36,
  salesTax: 10.25,
  totalFees: 1200,
  rebates: 500,
};

export const DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  rebates: 0,
  downPayment: 1700,
};

export const DUMMY_LEASE_WITH_PERCENTAGE_RV = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  rv: 57,
  isRVPercent: true,
};

export const RV_VALUE = 13110;
export const RV_PERCENTAGE = 57;
export const ACQUISITION_FEE_TOYOTA = 650;
export const DISPOSITION_FEE_TOYOTA = 350;

export const WHEN_TAXED_ON_MONTHLY_PAYMENT = {
  APR: 3,
  OFF_MSRP: 8.7,
  MSRP_PERCENTAGE: 1.35,
  PAYMENT_ZERO_DOWN_PRE_TAX: 282.12,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF_PRE_TAX: 287.45,
  PAYMENT_ZERO_DOWN: 311.04,
  PAYMENT_WITH_DOWN: 272.64,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF: 316.91,
  TOTAL_LEASE_COST_ZERO_DOWN: 13587.11,
  TOTAL_LEASE_COST_WITH_DOWN: 14078.82,
  TOTAL_LEASE_COST_ZERO_DOWN_ZERO_DRIVEOFF: 11441.98,
  DRIVEOFF_AMOUNT: 1005.26,
};

export const DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_SALES_PRICE = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TaxationMethod.TAX_ON_SALES_PRICE,
};

export const DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_SALES_PRICE = {
  ...DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TaxationMethod.TAX_ON_SALES_PRICE,
};

export const WHEN_TAXED_ON_SALES_PRICE = {
  MSRP_PERCENTAGE: 1.23,
  PAYMENT_ZERO_DOWN_PRE_TAX: 282.12,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF_PRE_TAX: 351.64,
  PAYMENT_ZERO_DOWN: 282.12,
  PAYMENT_WITH_DOWN: 247.29,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF: 351.64,
  TOTAL_LEASE_COST_ZERO_DOWN: 14508.95,
  TOTAL_LEASE_COST_WITH_DOWN: 14954.95,
  TOTAL_LEASE_COST_ZERO_DOWN_ZERO_DRIVEOFF: 12657.42,
  DRIVEOFF_AMOUNT: 3064.3,
};

export const DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_LEASE_PAYMENT = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TaxationMethod.TAX_ON_TOTAL_LEASE_PAYMENT,
};

export const DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_LEASE_PAYMENT = {
  ...DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TaxationMethod.TAX_ON_TOTAL_LEASE_PAYMENT,
};

export const WHEN_TAXED_ON_LEASE_PAYMENT = {
  MSRP_PERCENTAGE: 1.23,
  PAYMENT_ZERO_DOWN_PRE_TAX: 300.99,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF_PRE_TAX: 322.14,
  PAYMENT_ZERO_DOWN: 282.12,
  PAYMENT_WITH_DOWN: 247.29,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF: 322.14,
  TOTAL_LEASE_COST_ZERO_DOWN: 13622.99,
  TOTAL_LEASE_COST_WITH_DOWN: 14114.7,
  TOTAL_LEASE_COST_ZERO_DOWN_ZERO_DRIVEOFF: 11624.83,
  DRIVEOFF_AMOUNT: 1980.36,
};
