import { TaxationMethod } from "../src/constants";

export const DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT = {
  make: "Toyota",
  msrp: 23000,
  sellingPrice: 21000,
  rv: 13110,
  isRVPercent: false,
  mf: 0.00125,
  leaseTerm: 36,
  salesTax: 10.25,
  totalFees: 1200,
  rebates: 500,
};

export const DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  rebates: 0,
  downPayment: 1700,
};

export const DUMMY_LEASE_WITH_PERCENTAGE_RV = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  rv: 57,
  isRVPercent: true,
};

export const RV_VALUE = 13110;
export const RV_PERCENTAGE = 57;
export const ACQUISITION_FEE_TOYOTA = 650;
export const DISPOSITION_FEE_TOYOTA = 350;

export const WHEN_TAXED_ON_MONTHLY_PAYMENT = {
  APR: 3,
  OFF_MSRP: 8.7,
  MSRP_PERCENTAGE: 1.19,
  BASE_PAYMENT: 205.28,
  RENT_CHARGE: 42.01,
  PAYMENT_ZERO_DOWN_PRE_TAX: 247.29,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF_PRE_TAX: 310.8,
  PAYMENT_ZERO_DOWN: 272.64,
  PAYMENT_WITH_DOWN: 234.23,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF: 342.65,
  TOTAL_LEASE_COST_ZERO_DOWN: 12255.82,
  TOTAL_LEASE_COST_WITH_DOWN: 12696.29,
  TOTAL_LEASE_COST_ZERO_DOWN_ZERO_DRIVEOFF: 12342.83,
  DRIVEOFF_AMOUNT: 2363.51,
};

export const DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_SALES_PRICE = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TaxationMethod.TAX_ON_SALES_PRICE,
};

export const DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_SALES_PRICE = {
  ...DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TaxationMethod.TAX_ON_SALES_PRICE,
};

export const WHEN_TAXED_ON_SALES_PRICE = {
  MSRP_PERCENTAGE: 1.08,
  PAYMENT_ZERO_DOWN_PRE_TAX: 282.12,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF_PRE_TAX: 372.52,
  PAYMENT_ZERO_DOWN: 247.29,
  PAYMENT_WITH_DOWN: 212.46,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF: 372.52,
  TOTAL_LEASE_COST_ZERO_DOWN: 13254.95,
  TOTAL_LEASE_COST_WITH_DOWN: 13700.95,
  TOTAL_LEASE_COST_ZERO_DOWN_ZERO_DRIVEOFF: 13388.05,
  DRIVEOFF_AMOUNT: 4249.79,
};

export const DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_LEASE_PAYMENT = {
  ...DUMMY_LEASE_ZERO_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TaxationMethod.TAX_ON_TOTAL_LEASE_PAYMENT,
};

export const DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_LEASE_PAYMENT = {
  ...DUMMY_LEASE_WITH_DOWN_WITH_TAX_ON_MONTHLY_PAYMENT,
  taxMethod: TaxationMethod.TAX_ON_TOTAL_LEASE_PAYMENT,
};

export const WHEN_TAXED_ON_LEASE_PAYMENT = {
  MSRP_PERCENTAGE: 1.08,
  PAYMENT_ZERO_DOWN_PRE_TAX: 300.99,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF_PRE_TAX: 348.98,
  PAYMENT_ZERO_DOWN: 247.29,
  PAYMENT_WITH_DOWN: 212.46,
  PAYMENT_ZERO_DOWN_ZERO_DRIVEOFF: 348.98,
  TOTAL_LEASE_COST_ZERO_DOWN: 12291.7,
  TOTAL_LEASE_COST_WITH_DOWN: 12732.16,
  TOTAL_LEASE_COST_ZERO_DOWN_ZERO_DRIVEOFF: 12564.24,
  DRIVEOFF_AMOUNT: 3286.54,
};

// Finance constants

export const DUMMY_FINANCE_WITH_ZERO_DOWN_WITH_ZERO_TAX_WITH_ZERO_FEES = {
  sellingPrice: 49000,
  APR: 1.5,
  financeTerm: 60,
};

export const DUMMY_FINANCE_WITH_DOWN_PAYMENT_WITH_ZERO_TAX_WITH_ZERO_FEES = {
  ...DUMMY_FINANCE_WITH_ZERO_DOWN_WITH_ZERO_TAX_WITH_ZERO_FEES,
  downPayment: 2000,
};

export const DUMMY_FINANCE_WITH_ZERO_DOWN_WITH_TAX_WITH_ZERO_FEES = {
  ...DUMMY_FINANCE_WITH_ZERO_DOWN_WITH_ZERO_TAX_WITH_ZERO_FEES,
  salesTax: 6.25,
};

export const DUMMY_FINANCE_WITH_ZERO_DOWN_WITH_ZERO_TAX_WITH_FEES = {
  ...DUMMY_FINANCE_WITH_ZERO_DOWN_WITH_ZERO_TAX_WITH_ZERO_FEES,
  untaxableFees: 500,
  taxableFees: 1000,
};

export const DUMMY_FINANCE_WITH_DOWN_PAYMENT_WITH_TAX_WITH_FEES = {
  ...DUMMY_FINANCE_WITH_ZERO_DOWN_WITH_ZERO_TAX_WITH_ZERO_FEES,
  downPayment: 2000,
  salesTax: 6.25,
  untaxableFees: 500,
  taxableFees: 1000,
};

export const DUMMY_FINANCE_WITH_TRADE_IN = {
  ...DUMMY_FINANCE_WITH_ZERO_DOWN_WITH_ZERO_TAX_WITH_ZERO_FEES,
  tradeIn: 2000,
};

export const WHEN_ZERO_DOWN_ZERO_TAX_ZERO_FEES = {
  MONTHLY_PAYMENT: 848.18,
  TOTAL_COST: 50891.07,
  TOTAL_INTEREST: 1891.07,
};

export const WHEN_DOWN_PAYMENT_ZERO_TAX_ZERO_FEES = {
  MONTHLY_PAYMENT: 813.56,
  TOTAL_COST: 50813.88,
  TOTAL_INTEREST: 1813.88,
};

export const WHEN_ZERO_DOWN_TAX_ZERO_FEES = {
  MONTHLY_PAYMENT: 901.2,
  TOTAL_COST: 54071.76,
  TOTAL_AMOUNT_TO_FINANCE: 52062.5,
  TOTAL_INTEREST: 2009.26,
};

export const WHEN_ZERO_DOWN_ZERO_TAX_AND_FEES = {
  MONTHLY_PAYMENT: 874.15,
  TOTAL_COST: 52448.96,
  TOTAL_AMOUNT_TO_FINANCE: 50500,
  TOTAL_INTEREST: 1948.96,
};

export const WHEN_DOWN_PAYMENT_TAX_AND_FEES = {
  MONTHLY_PAYMENT: 893.62,
  TOTAL_COST: 55617.38,
  TOTAL_AMOUNT_TO_FINANCE: 51625,
  TOTAL_INTEREST: 1992.38,
};
