export enum TaxationMethod {
  TAX_ON_MONTHLY_PAYMENT = 1,
  TAX_ON_SALES_PRICE,
  TAX_ON_TOTAL_LEASE_PAYMENT,
}

export const MAKES = [
  { id: 1, displayName: "Acura", acquisitionFee: 595 },
  {
    id: 2,
    displayName: "Alfa Romeo",
    acquisitionFee: 595,
    dispositionFee: 395,
  },
  { id: 3, displayName: "Audi", acquisitionFee: 895, dispositionFee: 495 },
  {
    id: 4,
    displayName: "Bmw",
    acquisitionFee: 925,
    dispositionFee: 350,
    mfReductionUnit: 0.00007,
  },
  { id: 5, displayName: "Buick", acquisitionFee: 650, dispositionFee: 495 },
  { id: 6, displayName: "Cadillac", acquisitionFee: 650, dispositionFee: 595 },
  { id: 7, displayName: "Chevrolet", acquisitionFee: 650, dispositionFee: 395 },
  { id: 8, displayName: "Chrysler", acquisitionFee: 595, dispositionFee: 395 },
  { id: 9, displayName: "Dodge", acquisitionFee: 595, dispositionFee: 395 },
  { id: 10, displayName: "Fiat", acquisitionFee: 595, dispositionFee: 395 },
  { id: 11, displayName: "Ford", acquisitionFee: 645, dispositionFee: 395 },
  { id: 12, displayName: "Genesis", acquisitionFee: 595, dispositionFee: 400 },
  { id: 13, displayName: "GMC", acquisitionFee: 650, dispositionFee: 495 },
  { id: 14, displayName: "Honda", acquisitionFee: 595, dispositionFee: 0 },
  { id: 15, displayName: "Hyundai", acquisitionFee: 595, dispositionFee: 400 },
  {
    id: 16,
    displayName: "Infiniti",
    acquisitionFee: 700,
    dispositionFee: 395,
    mfReductionUnit: 0.0001,
  },
  { id: 17, displayName: "Jaguar", acquisitionFee: 895, dispositionFee: 300 },
  { id: 18, displayName: "Jeep", acquisitionFee: 795, dispositionFee: 395 },
  { id: 19, displayName: "Kia", acquisitionFee: 595, dispositionFee: 400 },
  {
    id: 20,
    displayName: "land rover",
    acquisitionFee: 895,
    dispositionFee: 300,
  },
  {
    id: 21,
    displayName: "Lexus",
    acquisitionFee: 795,
    dispositionFee: 350,
    mfReductionUnit: 0.00008,
  },
  { id: 22, displayName: "Lincoln", acquisitionFee: 645, dispositionFee: 0 },
  { id: 23, displayName: "Mini", acquisitionFee: 925, dispositionFee: 350 },
  { id: 24, displayName: "Mazda", acquisitionFee: 595, dispositionFee: 300 },
  {
    id: 25,
    displayName: "Mercedes benz",
    acquisitionFee: 795,
    dispositionFee: 595,
    mfReductionUnit: 0.00007,
  },
  { id: 26, displayName: "Mitsubishi", acquisitionFee: 595, dispositionFee: 0 },
  { id: 27, displayName: "Nissan", acquisitionFee: 650, dispositionFee: 395 },
  { id: 28, displayName: "Ram", acquisitionFee: 595, dispositionFee: 395 },
  {
    id: 29,
    displayName: "Scion",
    acquisitionFee: 650,
    dispositionFee: 350,
    mfReductionUnit: 0.00008,
  },
  { id: 30, displayName: "Smart", acquisitionFee: 295, dispositionFee: 395 },
  { id: 31, displayName: "Subaru", acquisitionFee: 595, dispositionFee: 300 },
  { id: 32, displayName: "Tesla", acquisitionFee: 695, dispositionFee: 395 },
  {
    id: 33,
    displayName: "Toyota",
    acquisitionFee: 650,
    dispositionFee: 350,
    mfReductionUnit: 0.00008,
  },
  {
    id: 34,
    displayName: "Volkswagen",
    acquisitionFee: 675,
    dispositionFee: 395,
  },
  { id: 35, displayName: "Volvo", acquisitionFee: 995, dispositionFee: 350 },
];
